# Ecommerce Purchase

In [2]:
import numpy as np
import pandas as pd

In [6]:
data = pd.read_csv(r'/Users/gavinhenderson/Desktop/pythonpathtodatascience/practiceProjects/Ecommerce Purchases')

### 1. Display Top 10 Rows of the Dataset

In [9]:
data.head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

### 2. Check last 10 rows of the dataset

In [10]:
data.tail(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9990,"75731 Molly Springs\nWest Danielle, VT 96934-5102",93 ty,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4;...,"Pace, Vazquez and Richards",869968197049750,04/24,877,JCB 15 digit,andersonmichael@sherman.biz,Early years teacher,54.170.3.185,ru,18.35
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

### 3. Check Datatype of each column

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

### 4. Check Null values in the dataset

In [12]:
data.isnull().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

### 5. How Many Rows and Columns in our Dataset

In [14]:
print('There are ', data.shape[0], 'Rows')
print('There are', data.shape[1], 'Columns')

There are  10000 Rows
There are 14 Columns

OR

In [15]:
len(data.columns)

14

In [16]:
len(data)

10000

### 6. Highest and lowest purchase price

In [17]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [18]:
data['Purchase Price'].max()

99.99

In [20]:
data['Purchase Price'].min()

0.0

### 7. Average Purchase Price

In [21]:
data['Purchase Price'].mean()

50.347302

### 8. How many people have French 'fr' as their language?

In [22]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [25]:
data[data['Language'].isin(['fr'])]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
19,"125 Hall Summit\nBoothton, IL 41721",99 CU,PM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Turner-Mckinney,676343504830,02/20,440,VISA 16 digit,ruiznicole@gmail.com,"Designer, interior/spatial",25.105.209.214,fr,58.39
53,"PSC 9431, Box 7059\nAPO AA 29285-1363",14 qD,AM,Opera/9.34.(X11; Linux x86_64; it-IT) Presto/2...,"Higgins, Cardenas and Kennedy",869972604798355,08/17,157,JCB 16 digit,amorales@yahoo.com,Technical author,44.108.117.122,fr,10.41
76,"49206 Campbell Port\nNorth Cliffordshire, HI 3...",71 iu,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_9...,Jacobs-Tucker,6011343518820988,01/17,806,Voyager,eperez@hotmail.com,Paramedic,210.207.58.168,fr,57.34
82,493 Smith Valleys Suite 004\nNew Madelineville...,35 ls,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_0 like M...,"Robinson, Johnston and Valdez",4351359627548412,06/17,937,VISA 13 digit,amendez@yahoo.com,"Engineer, materials",163.129.163.100,fr,49.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9947,"32827 Carl Inlet\nSouth Nicole, NY 38081-6636",40 Dp,PM,Mozilla/5.0 (Windows; U; Windows 95) AppleWebK...,Pruitt-Flores,3158564208754951,03/17,386,Mastercard,josephsmith@gmail.com,Textile designer,198.68.38.23,fr,49.61
9951,"518 Brown Dam\nGarciaside, IN 33057",71 wq,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,"Crosby, Vasquez and Ballard",5256758441931287,12/17,146,VISA 16 digit,cjennings@yahoo.com,"Lighting technician, broadcasting/film/video",58.12.83.1,fr,57.59
9977,"02182 Keith Expressway\nEast Shannon, CT 20578...",34 RL,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Deleon, Jacobson and Benton",4186094003664688,06/21,397,JCB 16 digit,daltoncarter@yahoo.com,Biomedical engineer,146.238.118.2,fr,94.93
9980,"6061 Dave Lights\nPhillipsview, UT 40500",25 Mv,AM,Opera/8.58.(Windows NT 5.0; it-IT) Presto/2.9....,Cortez-Frye,6011944199756993,12/24,755,JCB 15 digit,mark74@kirby-stewart.org,Textile designer,110.103.77.195,fr,16.05

In [26]:
sum(data['Language'].isin(['fr']))

1097

OR

In [27]:
len(data[data['Language'].isin(['fr'])])

1097

### 9. Job Title Contains Engineer

In [28]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [29]:
data['Job']

0       Scientist, product/process development
1                            Drilling engineer
2                     Customer service manager
3                            Drilling engineer
4                                  Fine artist
                         ...
9995                                Printmaker
9996                           Energy engineer
9997                        Veterinary surgeon
9998                  Local government officer
9999                    Embryologist, clinical
Name: Job, Length: 10000, dtype: object

In [31]:
data[data['Job'].str.contains('Engineer', case= False)] # To make case-insensitive

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
55,"27635 Maureen Bypass Apt. 883\nSandraview, SD ...",59 LJ,AM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_3 like M...,Sims-Lyons,3158113629128344,09/19,857,VISA 16 digit,adkinsarthur@yahoo.com,"Engineer, broadcasting (operations)",227.235.89.210,pt,48.74
60,"7126 Katherine Squares\nPerkinsview, CO 97299-...",63 qu,AM,Opera/8.68.(X11; Linux x86_64; en-US) Presto/2...,Marshall-Fernandez,349767747049645,05/20,672,JCB 15 digit,sweeneyhannah@jones.biz,"Engineer, agricultural",197.144.142.102,de,20.43
64,"937 Weaver Isle Apt. 096\nTracyborough, KY 182...",97 QO,AM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_2 rv...,Villa Inc,869930676434762,11/21,578,Discover,jason24@gardner-anderson.com,"Engineer, civil (consulting)",218.171.210.9,it,72.45
82,493 Smith Valleys Suite 004\nNew Madelineville...,35 ls,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_0 like M...,"Robinson, Johnston and Valdez",4351359627548412,06/17,937,VISA 13 digit,amendez@yahoo.com,"Engineer, materials",163.129.163.100,fr,49.04
92,Unit 9659 Box 0618\nDPO AA 00377-5360,37 jN,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,"Williams, Goodman and Morris",4748275281424579,01/18,496,JCB 15 digit,psimmons@harrison-brown.info,"Engineer, land",10.172.75.245,zh,73.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9868,Unit 9129 Box 2546\nDPO AP 96513,78 Ei,AM,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.6.20) G...,Fowler-Villanueva,377635852162559,10/16,672,American Express,maryward@lane-reed.com,"Engineer, building services",101.29.252.241,de,25.88
9922,"0850 Joseph Estate Apt. 649\nNew Brookefort, K...",82 SJ,AM,Opera/8.29.(Windows NT 5.01; sl-SI) Presto/2.9...,"Anderson, Charles and Alexander",676344664773,12/19,572,VISA 16 digit,keith96@ross-garrett.info,"Engineer, electrical",225.184.17.88,fr,68.13
9925,"09281 Mills Court Apt. 022\nWatkinstown, WI 83...",15 PM,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5342...,Parker PLC,4872299411791,11/22,974,Diners Club / Carte Blanche,xholloway@cook-coleman.info,"Engineer, materials",175.188.141.23,fr,91.75
9945,"693 Gomez Keys\nWest Marcushaven, SC 32366-3890",60 tG,PM,Mozilla/5.0 (Windows NT 6.2) AppleWebKit/5350 ...,Clay-Johnson,4474423068651820,10/17,216,JCB 15 digit,kyle97@gmail.com,"Engineer, materials",123.237.158.173,pt,51.68
9952,"9991 Vaughn Hills\nRacheltown, PA 55409",36 KC,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,"Ward, Smith and Castillo",6011679271321726,09/19,964,Voyager,jonesjennifer@olson.com,"Engineer, energy",116.228.12.42,es,39.63

In [32]:
len(data[data['Job'].str.contains('Engineer', case= False)]) # To make case-insensitive

984

### Find email of the person with the following IP address: 132.207.160.22

In [33]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [34]:
data['IP Address']

0       149.146.147.205
1          15.160.41.51
2        132.207.160.22
3          30.250.74.19
4          24.140.33.94
             ...
9995      29.73.197.114
9996     121.133.168.51
9997      156.210.0.254
9998       55.78.26.143
9999    176.119.198.199
Name: IP Address, Length: 10000, dtype: object

In [38]:
data[data['IP Address'] == '132.207.160.22']['Email']

2    amymiller@morales-harrison.com
Name: Email, dtype: object

### 11. How many people have a MasterCard as their credit card provider and made a purchase above 50

In [40]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [46]:
data[(data['CC Provider'] == 'Mastercard') & (data['Purchase Price'] > 50)]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
18,"461 Christopher Square\nWest Michaelchester, C...",17 SB,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Beard, Abbott and Pena",6011350184276270,12/22,767,Mastercard,hannah63@yahoo.com,Photographer,73.250.176.201,el,70.15
31,USNS Alvarado\nFPO AA 27052-1231,26 Lh,PM,Opera/8.84.(X11; Linux i686; sl-SI) Presto/2.9...,Nicholson Group,4614997834548,03/22,909,Mastercard,ashley12@hotmail.com,Sales executive,94.176.142.201,en,94.14
35,"93392 Webb Gardens Apt. 220\nLaurabury, AR 999...",37 om,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Mora Ltd,6011049630969815,09/16,367,Mastercard,hgonzalez@mcdowell.com,"Lecturer, further education",216.23.95.40,zh,97.46
90,"431 Bowen Lights\nFergusonborough, MH 01362",31 tG,AM,Mozilla/5.0 (Windows NT 5.2; it-IT; rv:1.9.1.2...,Copeland-Lee,639032576097,06/18,868,Mastercard,nrogers@brown.com,"Teacher, English as a foreign language",153.188.13.203,es,78.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9948,"95544 Johnson Isle Suite 939\nMichaelberg, RI ...",91 bW,AM,Opera/8.36.(X11; Linux x86_64; sl-SI) Presto/2...,Fox-Peterson,4762924304307,03/17,567,Mastercard,haleybenjamin@gmail.com,Structural engineer,120.36.140.58,en,71.89
9954,"051 Samantha Wells Apt. 328\nScottborough, OR ...",11 vG,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_2...,"Mendoza, Zimmerman and Reilly",30232295374907,05/21,762,Mastercard,brownamy@perkins.com,"Presenter, broadcasting",61.97.84.101,it,87.15
9981,"087 Larson Roads Apt. 587\nRicestad, WI 98077-...",95 Kw,AM,Opera/9.63.(Windows NT 5.01; en-US) Presto/2.9...,"Ortiz, Schultz and Adams",4690863684605,01/19,695,Mastercard,laurenbennett@richards.com,Environmental education officer,106.21.237.73,pt,63.61
9987,"2754 Klein Mission\nJohnsonview, PA 64925-9624",65 Fg,PM,Opera/9.26.(Windows CE; sl-SI) Presto/2.9.188 ...,Curtis LLC,180027305702263,12/24,865,Mastercard,denisehamilton@novak.biz,Primary school teacher,164.39.190.217,es,60.83

In [47]:
len(data[(data['CC Provider'] == 'Mastercard') & (data['Purchase Price'] > 50)])

405

In [48]:
data[(data['CC Provider'] == 'Mastercard') & (data['Purchase Price'] > 50)].count()

Address             405
Lot                 405
AM or PM            405
Browser Info        405
Company             405
Credit Card         405
CC Exp Date         405
CC Security Code    405
CC Provider         405
Email               405
Job                 405
IP Address          405
Language            405
Purchase Price      405
dtype: int64

### 12. Find Email of the Person Witht the Following Credit Card Number: 4664825258997302

In [49]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [57]:
data[data['Credit Card'] == 4664825258997302]['Email']

9992    bberry@wright.net
Name: Email, dtype: object

### 13. How many people purchase in the AM and how many purchase in the PM

In [58]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [61]:
data['AM or PM'].value_counts()

PM    5068
AM    4932
Name: AM or PM, dtype: int64

### 14. How many people have a credit card that expires in 2020

In [62]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [67]:
data['CC Exp Date']

0       02/20
1       11/18
2       08/19
3       02/24
4       10/25
        ...
9995    03/22
9996    07/25
9997    05/21
9998    11/17
9999    02/19
Name: CC Exp Date, Length: 10000, dtype: object

In [69]:
def fun():
    count =0 
    for date in data['CC Exp Date']:
        if date.split('/')[1] == '20':
            count = count + 1
        print(count)

In [70]:
fun()

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
4
4
5
5
5
6
7
7
7
7
8
9
9
9
9
9
9
9
9
9
9
9
9
10
11
11
11
11
11
11
11
12
12
12
12
12
12
12
12
12
12
12
12
12
13
13
13
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
15
15
15
15
15
15
15
15
15
15
15
15
15
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
18
18
18
18
18
18
18
18
19
20
20
20
20
20
20
20
20
21
21
21
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
24
24
24
24
25
25
25
26
26
26
26
26
26
26
26
26
27
27
27
27
27
27
28
28
28
28
28
28
28
28
28
28
28
28
28
29
29
30
30
30
30
30
30
30
30
30
30
30
30
31
32
32
32
32
32
32
32
32
32
32
32
32
32
32
32
32
32
32
32
32
32
32
32
32
32
33
33
33
33
33
33
33
33
33
34
34
34
34
34
34
34
34
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
36
36
36
36
36
36
36
36
36
36
37
37
37
37
37
37
37
37
37
37
37
37
37
38
38
38
39
39
39
39
39
39
39
39
39
39
39
39
39
40
41
41
41
41
41
41
41
41
42
42
42
42
42
43
43
43
44
44
44
44
44
44
44
44
44
44
44
44
44
44
44
45
46
46
46
46
46
46
46
46
46
46
46
46
47
48
48
48
48
48
48
48
48
48
48
48
48
48
48
48
49
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
51
51
51
52
52
52
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
55
55
55
55
55
55
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
59
59
59
59
59
59
60
60
60
61
61
61
61
61
61
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
62
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
63
64
64
65
65
65
66
66
66
66
66
66
66
66
66
66
66
66
67
67
67
67
67
67
68
69
69
69
69
69
69
69
69
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
71
72
72
72
72
72
73
73
73
73
73
73
73
73
73
74
74
74
74
74
75
75
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
77
77
77
77
77
77
77
77
77
77
77
77
78
78
78
78
79
79
79
79
79
79
79
79
79
79
79
80
80
80
80
80
80
80
80
80
81
81
82
82
82
82
82
82
82
82
82
82
82
82
82
82
82
82
82
82
82
82
82
82
82
83
83
83
83
83
83
83
83
83
84
84
84
84
84
84
85
85
85
85
85
85
85
85
85
85
85
85
85
85
85
85
85
86
86
86
86
86
86
87
87
87
87
87
87
87
87
87
87
87
87
87
88
89
89
90
90
90
90
90
90
90
90
90
90
90
90
90
90
90
90
90
90
91
91
91
91
91
91
91
91
91
91
91
91
91
91
91
91
91
92
92
92
92
93
94
94
94
94
94
94
94
94
94
95
95
95
95
96
97
97
97
97
97
97
97
97
97
97
97
97
97
97
97
97
97
97
97
97
97
98
98
98
98
98
99
100
100
100
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
102
102
102
102
102
102
102
103
103
103
103
103
104
104
104
104
104
104
104
104
104
104
104
104
104
104
104
104
104
104
104
105
105
105
105
105
105
105
106
107
107
107
107
107
107
107
107
107
107
107
107
107
107
107
107
107
107
107
107
107
107
107
107
107
108
108
108
108
108
108
108
108
108
108
109
109
109
109
109
110
110
110
110
110
110
110
110
110
111
112
112
112
112
112
112
113
113
113
113
113
113
114
114
114
114
114
114
114
114
114
114
115
115
115
115
115
115
115
115
115
116
116
116
116
116
116
116
117
117
118
118
118
118
118
118
118
118
118
118
119
120
120
120
120
120
120
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
122
122
122
122
122
123
123
123
123
123
123
123
123
123
123
123
123
123
123
123
123
124
124
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
125
126
126
126
126
126
127
127
127
127
127
127
127
127
127
127
127
128
128
128
128
128
128
128
128
129
129
129
129
129
129
129
130
130
130
130
130
130
130
130
130
130
130
130
130
131
131
131
131
131
131
131
131
131
131
131
131
131
131
131
131
131
132
132
132
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
133
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
134
135
135
135
135
135
135
135
135
135
135
135
135
135
135
136
136
136
136
136
136
136
136
136
136
136
136
136
136
137
137
137
137
137
137
137
137
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
139
139
139
139
139
139
140
140
140
140
140
140
140
140
140
140
140
140
140
141
141
141
141
141
141
142
143
143
143
143
143
143
143
143
143
143
143
143
143
143
143
144
144
144
144
144
144
145
145
145
145
145
145
145
145
145
145
146
146
146
146
146
146
146
146
146
146
146
146
146
146
146
146
146
146
146
146
146
146
146
146
147
147
147
147
147
147
147
147
148
148
148
148
148
148
149
150
150
150
150
150
150
151
151
151
151
151
151
151
151
151
151
151
151
151
151
151
151
152
152
152
152
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
153
154
154
154
155
155
155
155
155
155
155
155
155
155
155
156
156
156
156
156
157
157
157
157
157
157
157
157
157
157
157
157
157
157
157
157
157
158
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
159
160
160
160
161
161
161
161
162
162
162
162
162
162
162
162
162
162
162
162
162
162
162
163
163
163
164
164
164
165
165
165
165
165
166
167
167
167
167
167
167
167
167
167
167
167
167
168
168
168
169
169
169
169
169
169
169
169
169
169
169
169
169
169
169
169
169
169
169
169
169
169
169
170
170
170
170
170
170
170
171
171
171
171
171
171
171
171
171
171
171
171
171
171
171
171
171
171
172
172
172
172
172
173
173
173
173
174
174
174
174
174
175
175
175
175
175
175
175
176
176
176
176
176
176
176
176
176
176
176
176
176
176
176
176
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
177
178
178
178
178
178
178
178
179
179
179
179
179
179
179
179
179
179
179
179
179
179
179
179
179
179
179
180
180
180
180
180
180
181
181
181
181
182
182
182
182
182
182
182
182
182
182
182
183
183
183
183
183
183
183
183
183
183
183
183
183
183
183
183
183
183
183
183
183
184
184
184
184
184
184
185
185
185
185
185
186
187
187
187
187
187
187
187
188
188
188
188
188
188
188
188
189
189
189
189
189
189
189
189
189
189
189
189
189
189
189
189
189
189
190
190
190
190
190
190
190
190
190
191
191
191
191
191
191
191
191
191
191
192
192
192
192
192
193
193
193
193
193
193
193
193
193
193
194
194
194
194
194
194
194
194
194
194
194
194
194
195
195
195
195
196
196
196
196
196
196
196
196
196
196
196
196
196
197
198
198
198
198
198
198
199
199
199
199
199
199
199
199
199
200
200
200
200
200
200
201
202
202
202
202
202
202
203
204
204
204
204
204
204
204
204
204
204
205
205
205
205
205
205
205
205
205
205
205
205
205
206
206
206
206
207
207
207
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
208
209
209
209
209
209
209
209
209
209
209
209
209
209
209
210
210
210
210
211
211
211
211
211
211
211
211
211
211
211
211
211
211
211
211
211
211
211
211
212
212
212
212
212
212
212
212
212
213
213
213
213
213
213
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
214
215
216
216
216
216
216
216
216
217
218
218
218
218
219
219
219
219
220
220
220
221
221
221
221
221
221
222
223
223
223
224
224
224
224
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
225
226
226
226
227
227
227
227
227
227
227
227
227
227
227
227
227
227
227
227
227
227
227
227
227
227
227
228
228
228
228
228
228
228
228
228
228
228
228
228
228
228
228
228
228
228
228
228
228
228
229
230
230
231
231
231
231
231
231
231
231
231
231
231
231
231
231
231
231
231
232
233
233
233
233
233
233
233
234
234
235
235
235
235
235
235
235
235
235
235
235
235
235
235
235
235
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
236
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
237
238
238
238
238
238
238
238
238
238
238
238
238
238
239
239
239
239
239
239
239
240
240
240
240
240
240
240
240
240
240
240
240
240
240
240
240
240
240
240
240
240
241
241
241
241
241
241
241
241
241
241
242
242
242
242
242
242
242
242
242
242
242
242
242
242
242
242
242
242
242
243
244
244
244
244
244
244
244
244
244
244
245
245
245
245
245
245
245
245
245
245
246
246
246
246
246
246
246
246
246
246
246
246
246
246
246
246
246
246
246
246
246
247
247
247
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
248
249
249
250
250
250
250
250
250
250
250
250
250
250
250
250
250
250
250
250
250
251
251
252
252
252
252
252
252
252
252
253
253
253
254
254
254
254
254
254
255
255
255
255
255
256
256
256
256
256
256
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
257
258
258
259
259
259
259
259
259
259
259
259
259
259
259
259
259
259
260
260
260
260
260
260
260
260
260
260
260
260
260
260
260
260
260
260
260
260
260
261
261
261
261
261
261
261
261
261
261
261
261
261
261
261
261
261
261
262
263
263
263
263
263
263
263
263
263
263
263
263
263
263
263
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
264
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
265
266
267
268
268
268
268
268
268
268
268
268
268
268
268
268
269
269
269
269
269
269
269
269
269
269
269
269
269
269
269
269
269
269
269
269
269
270
270
270
270
270
270
270
270
270
270
270
271
271
271
271
271
271
271
271
271
271
272
272
272
272
273
273
273
273
273
274
274
274
274
275
275
275
275
275
275
275
275
275
275
275
276
276
276
276
276
276
277
277
277
277
277
277
277
277
277
278
278
278
278
278
278
278
278
278
279
279
279
279
279
279
279
280
280
280
281
281
281
281
281
281
281
281
282
282
282
282
282
282
282
282
282
282
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
283
284
284
284
284
284
284
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
285
286
286
286
286
286
287
287
287
287
288
288
288
288
288
288
288
288
288
288
288
288
288
288
288
289
289
289
289
289
289
289
290
290
291
291
291
292
292
292
292
292
292
292
292
292
292
292
293
293
293
293
293
293
293
293
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
294
295
295
295
295
295
295
295
295
295
296
296
296
296
296
296
296
296
296
296
296
296
296
297
297
297
297
297
297
297
297
297
297
297
298
298
298
298
298
298
299
299
299
299
299
299
299
299
299
299
299
299
299
299
299
300
300
300
300
301
301
301
301
301
301
302
302
302
302
302
302
302
302
302
302
303
303
303
303
303
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
304
305
305
305
305
305
305
305
305
305
305
305
305
305
305
306
306
306
306
306
306
306
306
306
306
306
306
307
307
307
308
308
308
308
308
308
308
308
308
308
308
308
308
308
308
308
308
308
308
309
309
309
309
309
309
309
309
310
310
310
311
311
311
312
312
313
313
313
313
313
313
314
314
314
314
314
314
315
315
315
315
315
315
315
315
315
315
316
316
316
316
316
316
316
316
316
316
316
316
316
316
316
316
316
316
316
316
316
316
317
317
317
317
317
317
317
317
318
318
319
319
319
319
319
319
319
319
319
319
319
319
320
321
321
321
321
321
321
321
321
321
321
321
321
321
322
322
322
322
322
322
322
322
322
323
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
324
325
325
325
326
326
326
326
326
326
326
326
326
326
326
326
327
327
327
327
327
327
327
327
327
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
328
329
329
329
329
329
329
329
330
330
330
330
330
330
330
330
330
330
330
330
330
331
331
332
332
332
333
333
333
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
334
335
335
335
335
335
335
335
335
335
335
335
335
335
335
335
335
335
335
335
335
335
335
335
335
336
336
336
336
336
336
336
336
336
336
337
337
337
337
337
337
337
337
337
337
337
337
337
337
337
337
337
337
337
337
337
337
337
337
337
338
339
339
339
339
339
339
339
340
340
340
340
340
340
340
341
341
341
341
341
341
342
342
342
342
342
342
342
342
343
343
343
343
343
343
343
343
344
344
344
344
344
345
345
345
345
346
346
347
347
347
347
347
347
347
347
347
347
348
348
348
348
348
348
348
348
348
349
349
350
350
350
350
350
351
352
352
352
352
352
352
352
352
352
352
352
352
352
352
352
352
352
352
352
352
352
352
352
352
352
353
353
353
353
353
353
353
353
353
353
353
353
353
353
353
353
353
353
353
353
353
353
353
354
354
354
354
354
354
354
354
354
354
354
354
355
356
356
356
356
356
357
357
357
357
357
357
357
357
357
358
358
358
358
358
358
358
358
358
358
358
358
359
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
361
361
361
361
361
361
361
361
361
361
361
361
361
362
362
362
362
362
362
362
362
362
362
362
362
362
362
362
362
363
363
363
364
364
364
364
364
364
364
364
365
365
365
365
365
365
365
365
366
366
366
366
366
367
367
367
367
367
367
367
367
367
367
367
367
367
367
368
368
368
368
368
368
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
369
370
371
371
371
371
371
371
371
371
371
371
371
371
372
372
372
372
372
372
372
372
372
373
373
373
373
373
373
373
373
373
373
373
373
373
373
373
374
374
374
374
374
374
374
374
374
374
374
374
374
374
374
374
374
374
374
375
375
376
376
376
376
376
376
376
376
376
376
376
376
376
376
376
377
377
377
377
377
377
377
377
378
378
378
379
379
379
379
380
380
380
380
380
380
381
381
382
382
383
383
383
383
384
384
384
384
384
384
384
384
384
384
385
385
385
385
385
385
385
385
385
385
385
386
386
386
386
386
386
386
386
386
386
386
386
386
386
386
386
387
387
387
387
387
387
387
387
387
387
387
388
388
388
388
388
388
388
388
388
388
388
388
388
388
389
389
390
390
390
390
390
390
390
391
392
392
392
392
392
392
392
392
392
393
393
394
394
394
394
394
394
394
394
394
394
394
394
394
394
394
394
394
394
394
394
394
394
394
394
394
395
395
395
395
395
395
395
395
395
395
395
395
395
395
395
395
395
395
395
396
396
396
396
396
396
396
396
396
396
396
396
396
396
396
396
396
396
396
396
396
396
397
398
398
398
398
398
398
398
398
398
398
398
398
398
398
398
398
398
398
398
398
398
399
399
399
399
399
399
399
399
400
400
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
401
402
402
402
402
403
403
403
403
403
403
403
404
404
404
404
404
404
405
405
405
405
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
406
407
407
407
407
408
408
409
409
409
409
409
409
409
409
409
409
409
409
410
410
410
410
410
410
410
410
410
410
410
410
410
410
410
410
410
410
410
410
410
411
411
411
411
411
411
411
411
411
411
411
411
411
412
412
412
413
413
413
413
414
414
414
415
415
415
415
415
415
415
415
415
415
415
415
415
415
415
415
416
416
416
416
416
416
416
416
416
416
416
416
417
417
417
417
417
417
417
417
417
418
418
418
418
418
418
419
419
419
419
419
419
419
419
419
419
419
419
419
419
419
419
420
420
420
420
420
420
420
420
420
421
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
422
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
423
424
424
425
425
425
425
426
426
426
427
428
428
428
429
429
429
429
429
429
429
429
429
429
429
429
429
429
429
429
429
429
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
430
431
431
431
431
431
431
431
431
431
431
432
432
432
432
432
432
432
432
433
433
433
434
434
434
434
435
435
435
435
435
435
435
435
435
435
435
435
436
436
436
436
436
436
436
437
437
437
437
437
437
437
437
437
437
437
437
437
437
437
437
437
437
437
437
438
438
438
439
439
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
440
441
441
442
442
442
442
442
442
442
442
442
442
443
443
443
443
443
443
444
444
444
444
444
444
444
444
444
445
445
445
445
445
445
446
446
446
446
446
446
446
446
446
446
446
446
446
446
446
446
446
446
446
446
446
446
447
447
447
448
449
449
449
449
449
449
449
449
449
449
449
449
449
449
449
449
449
449
449
449
449
450
450
450
451
451
452
452
452
452
452
452
452
452
452
452
452
452
452
452
452
452
452
452
453
453
453
453
453
454
454
454
454
454
454
454
454
454
454
454
454
455
455
455
455
455
455
456
456
456
456
456
456
456
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
457
458
458
458
458
458
458
458
458
458
458
458
459
459
459
459
459
459
459
459
460
460
460
460
461
461
461
461
461
461
461
461
461
461
461
461
461
462
462
463
463
463
464
464
464
464
465
465
465
465
466
466
466
466
466
466
466
466
466
467
467
467
467
467
467
467
468
468
469
469
469
469
469
470
471
471
471
471
471
471
471
471
471
471
471
471
471
471
471
472
472
472
473
473
474
474
474
474
474
474
474
474
474
474
474
474
474
474
474
474
475
475
475
475
475
475
476
476
476
476
476
476
476
476
476
476
476
476
476
476
476
476
476
476
476
476
476
476
476
476
477
477
477
478
478
478
478
478
478
478
479
480
480
481
481
481
481
481
481
481
481
482
483
483
483
483
483
483
483
483
483
484
484
484
484
484
484
484
484
484
484
484
484
484
484
484
484
484
485
486
486
486
486
486
486
486
486
486
486
486
486
486
486
487
487
487
487
487
487
487
487
487
488
488
488
488
488
488
488
488
488
488
488
488
488
488
488
488
488
488
488
489
490
490
490
490
490
490
490
490
490
490
490
490
490
491
491
491
491
491
491
492
492
492
493
493
493
493
493
493
493
494
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
495
496
496
496
496
496
496
496
497
497
497
497
497
497
498
498
498
498
499
499
499
499
499
500
500
500
500
500
500
501
501
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
502
503
503
503
503
503
503
504
504
504
505
505
505
505
505
505
505
505
505
505
505
506
506
506
506
506
507
507
507
507
507
507
507
507
507
507

In [71]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

Preferred Method

In [74]:
data[data['CC Exp Date'].apply(lambda x:x[3:] == '20')].count()

Address             988
Lot                 988
AM or PM            988
Browser Info        988
Company             988
Credit Card         988
CC Exp Date         988
CC Security Code    988
CC Provider         988
Email               988
Job                 988
IP Address          988
Language            988
Purchase Price      988
dtype: int64

### 15. Top 5 Most Popular Email providers

In [75]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [79]:
list1 = []
for email in data['Email']:
    list1.append(email.split('@')[1])

In [80]:
data['temp'] =list1

In [81]:
data.head(1)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,temp
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,yahoo.com

In [87]:
data['temp'].value_counts().head()

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: temp, dtype: int64

OTher method

In [88]:
data['Email'].apply(lambda x:x.split ('@')[1]).value_counts().head()

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: Email, dtype: int64